name: 機能リクエスト
description: 新しい機能の提案をするためのテンプレート
title: "[FEATURE] "
labels: ["enhancement", "需要調査"]
assignees:
  - tenpei-peso
body:
  - type: markdown
    attributes:
      value: |
        機能リクエストをありがとうございます！新しい機能について詳しく教えてください。

  - type: textarea
    id: feature-description
    attributes:
      label: 機能の説明
      description: 提案する機能について明確で簡潔な説明をしてください。
      placeholder: 提案する機能の詳細な説明...
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 解決したい問題
      description: この機能がどのような問題を解決するかを説明してください。
      placeholder: 現在抱えている問題や課題...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 提案する解決策
      description: どのような解決策を考えているかを説明してください。
      placeholder: 具体的な解決策の提案...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 検討した代替的な解決策があれば説明してください。
      placeholder: 他に考えられる解決策...

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の優先度をどのように考えていますか？
      options:
        - 高（すぐに必要）
        - 中（近いうちに必要）
        - 低（将来的にあると良い）
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: 実装の複雑さ（予想）
      description: この機能の実装はどの程度複雑だと思いますか？
      options:
        - 簡単（数時間〜1日）
        - 普通（2-5日）
        - 複雑（1週間以上）
        - 不明

  - type: checkboxes
    id: affected-platforms
    attributes:
      label: 影響を受けるプラットフォーム
      description: この機能はどのプラットフォームに影響しますか？
      options:
        - label: Android
        - label: iOS
        - label: Web
        - label: Windows
        - label: macOS
        - label: Linux

  - type: textarea
    id: mockups
    attributes:
      label: モックアップ・図表
      description: 可能であれば、機能のモックアップや図表を追加してください。
      placeholder: 画像やリンクをここに...

  - type: textarea
    id: additional-context
    attributes:
      label: 追加情報
      description: この機能リクエストについて他に関連する情報があれば、こちらに追加してください。
      placeholder: その他の関連情報...

  - type: checkboxes
    id: terms
    attributes:
      label: 確認事項
      description: 以下の項目を確認してください
      options:
        - label: 既存のIssueで同様の機能リクエストがないことを確認しました
          required: true
        - label: この機能がプロジェクトの目標と一致していると思います
          required: true